version: 2
jobs:
  build: &build
    docker:
      - image: mpppk/gored
    working_directory: /go/src/github.com/mpppk/gored
    steps:
      - checkout
      - run: make coverage -f Makefile
  release:
    <<: *build
    steps:
      - checkout
      - run: make bump-and-commit -f Makefile
      - run: make release -f Makefile
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
