version: 2
jobs:
  build:
    docker: &build
      - image: {{ .DockerImage }}
    working_directory: /go/src/github.com/{{ .UserName }}/{{ .RepoName }}
    steps:
      - checkout
      - run: make test -f {{ .MakefilePath }}
  release:
    <<: *build
    steps:
      - checkout
      - run: make bump-and-commit -f {{ .MakefilePath }}
      - run: make release -f {{ .MakefilePath }}
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
